# Generated by Django 4.1.2 on 2022-11-10 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetable',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='notetable',
            name='text',
            field=models.TextField(max_length=400, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='notetable',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='編集日時'),
        ),
    ]
