# Generated by Django 4.1.3 on 2022-11-27 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_notetable_created_at_alter_notetable_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notetable",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="イメージ画像"
            ),
        ),
        migrations.AlterField(
            model_name="notetable",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="最終変更日時"
            ),
        ),
    ]
